# Generated by Django 5.1.5 on 2025-04-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_portal', '0002_remove_coursevideo_course_topic_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(upload_to='course_video/'),
        ),
    ]
