# Generated by Django 5.1.5 on 2025-02-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0003_courses_course_rating_alter_testimonial_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffers',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialoffers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
