# Generated by Django 5.1.5 on 2025-02-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0007_courses_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='instructor',
        ),
    ]
