# Generated by Django 5.1.5 on 2025-02-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0008_remove_courses_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(help_text='in months', max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(null=True, upload_to='testimonials/'),
        ),
    ]
