# Generated by Django 5.1.5 on 2025-02-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0009_alter_courses_duration_alter_testimonial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
