# Generated by Django 5.1.5 on 2025-02-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0011_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
