# Generated by Django 5.1.5 on 2025-03-23 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0013_alter_blogpost_blog_image_alter_courses_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'instructor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
