# Generated by Django 5.1.5 on 2025-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0014_courses_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='syllabus',
            field=models.TextField(null=True),
        ),
    ]
