# Generated by Django 5.1.5 on 2025-03-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0015_courses_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_material',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
    ]
