# Generated by Django 5.1.5 on 2025-03-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_joblisting_is_active_joblisting_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
