# Generated by Django 5.1.5 on 2025-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0003_joblisting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
